# Generated by Django 6.0.7 on 2026-07-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
