# Generated by Django 6.0.7 on 2026-07-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Grade',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
