# Generated by Django 6.0.7 on 2026-07-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Grade',
        ),
    ]
